### ISSUE TITLE
Demo Checklist

### ISSUE THREAD

**Issue by mdworken** [mdworken/mkdbikeshare#3]
- [ ] Finish writing tests

- [x] Deploy to Heroku

- [x] Train Slackbot to make API calls

- [x] Configure app to push to Web Sockets

**Comment by mdworken** [comment]
Woah, got 3/4 fully done today, and made a lot of progress on the remaining one!
